server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: 192.168.0.103
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eager-load:
    # 让Ribbon在应用启动时就初始化,多个用,分隔
    clients: microservice-provider-user

management:
  endpoint:
    health:
      #是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        #将hystrix监控端点暴漏出来
        include: 'hystrix.stream'
