server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  zipkin:
    base-url: http://localhost:9411
  sleuth:
     sampler:
      # 采样率，模式0.1，也就是10%，为了便于观察效果，改为1.0，也就是100%。生产环境建议保持默认。
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG